"""Read-only adapter over the RoboCasa unified skill graph (annotation-derived).

The graph is GENERATED by ``sims/robocasa/robocasa/scripts/build_skill_taxonomy.py``
from the RoboCasa365 target-composite annotations and lives at
``sims/robocasa/skill_annotation_analysis/taxonomy/unified_skill_graph.json``.
This module never writes it, never re-scans the datasets or videos, and copies
nothing out of it into a second source of truth: every query reads the one
loaded document.

Five edge relations, kept DISTINCT (the graph's own ``relation_semantics``):

- ``IS_A``                 taxonomy child -> parent; retrieval + progressive disclosure
- ``HAS_STAGE``            observed skill -> its ordered annotation stages
- ``REALIZES``             observed stage -> the canonical skill interface it implements
- ``DECOMPOSES_TO``        composite -> ordered canonical component (ontology-authored)
- ``OBSERVED_TRANSITION``  stage -> next stage; empirical adjacency, NOT causality

A graph node marked ``executable: true`` means "a robot could do this kind of
thing" in the annotator's ontology. It is NOT an execution binding. Whether a
skill can be dispatched is decided by physical-harness skill records and task
bindings (``plugins/task/skill_planning.py``), never by this file.

Stdlib-only so it imports in every venv (``tests/test_kernel.py``: harness
imports no plugin, no third party beyond numpy).
"""

from __future__ import annotations

import hashlib
import json
import os
import re
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

#: The schema versions this adapter knows how to read.
SUPPORTED_SCHEMA_VERSIONS = frozenset({"1.0"})

#: The closed relation vocabulary. Anything else is a malformed graph.
RELATIONS = frozenset({"IS_A", "HAS_STAGE", "REALIZES", "DECOMPOSES_TO",
                       "OBSERVED_TRANSITION"})

#: Node kinds that name a SKILL a planner may select (categories/root/terminal
#: are navigation, stages are expansion output).
SKILL_KINDS = frozenset({"observed_skill", "canonical_skill"})

#: Where the graph lives on a fresh checkout of this workspace: the sibling
#: ``sims/`` tree. ``PH_UNIFIED_SKILL_GRAPH`` overrides it; nothing else names
#: the path (no per-caller literals).
GRAPH_PATH_ENV = "PH_UNIFIED_SKILL_GRAPH"
_REPO = Path(__file__).resolve().parent.parent
DEFAULT_GRAPH_PATH = (_REPO.parent / "sims" / "robocasa" / "skill_annotation_analysis"
                      / "taxonomy" / "unified_skill_graph.json")


def default_graph_path() -> Path:
    """The configured graph path: ``$PH_UNIFIED_SKILL_GRAPH`` else the
    workspace-relative default. Existence is NOT checked here -- ``load`` reports
    a missing file loudly, with the path it tried."""
    override = os.environ.get(GRAPH_PATH_ENV)
    return Path(override).expanduser() if override else DEFAULT_GRAPH_PATH


class SkillGraphError(ValueError):
    """A graph this adapter refuses to serve (malformed, cyclic, unknown skill)."""


# --- text ------------------------------------------------------------------

_STOP = frozenset({
    "a", "an", "the", "of", "to", "in", "on", "at", "from", "and", "or", "for",
    "with", "into", "onto", "please", "robot", "then", "it", "its", "is", "be",
    "up", "down", "some", "one", "me", "my", "i", "you", "this", "that",
})
_CAMEL = re.compile(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")
_WORD = re.compile(r"[a-z0-9]+")


def tokens(text: str) -> list[str]:
    """Deterministic retrieval tokens: camelCase split, lowercase, alnum runs,
    stop words dropped, a light plural/-ing strip. Pure function of the text."""
    out: list[str] = []
    for raw in _CAMEL.sub(" ", str(text)).split():
        for w in _WORD.findall(raw.lower()):
            if w in _STOP or len(w) < 2:
                continue
            if len(w) > 5 and w.endswith("ing"):
                w = w[:-3]
            elif len(w) > 3 and w.endswith("s") and not w.endswith("ss"):
                w = w[:-1]
            out.append(w)
    return out


# --- the graph -------------------------------------------------------------


@dataclass(frozen=True)
class Node:
    id: str
    name: str
    kind: str
    raw: Mapping[str, Any] = field(repr=False)


@dataclass(frozen=True)
class Leaf:
    """One executable-shaped step after expansion.

    ``skill`` is the graph skill this leaf belongs to (an observed skill or the
    canonical skill that stands alone); ``stage`` is its annotation stage name
    when the skill has HAS_STAGE edges (``None`` for a bare canonical leaf);
    ``canonical`` is the canonical interface (REALIZES target, or the skill
    itself when canonical); ``via`` names the relation that produced it.
    """

    skill: str
    stage: str | None
    canonical: str | None
    via: str
    taxonomy_path: tuple[str, ...]

    @property
    def label(self) -> str:
        return f"{self.skill}.{self.stage}" if self.stage else self.skill

    def as_dict(self) -> dict:
        return {"label": self.label, "skill": self.skill, "stage": self.stage,
                "canonical": self.canonical, "via": self.via,
                "taxonomy_path": list(self.taxonomy_path)}


class UnifiedSkillGraph:
    """The loaded, validated graph plus its read-only queries."""

    def __init__(self, data: Mapping[str, Any], *, source: str = "<memory>",
                 sha256: str | None = None) -> None:
        self.source = source
        self.sha256 = sha256
        self.schema_version = str(data.get("schema_version"))
        if self.schema_version not in SUPPORTED_SCHEMA_VERSIONS:
            raise SkillGraphError(
                f"unsupported schema_version {self.schema_version!r} "
                f"(supported: {sorted(SUPPORTED_SCHEMA_VERSIONS)})")
        self.root = str(data.get("root", ""))
        self.relation_semantics = dict(data.get("relation_semantics") or {})
        self.source_summary = dict(data.get("source_summary") or {})
        self._nodes: dict[str, Node] = {}
        self._by_name: dict[str, Node] = {}
        nodes = data.get("nodes")
        edges = data.get("edges")
        if not isinstance(nodes, list) or not isinstance(edges, list):
            raise SkillGraphError("graph.nodes and graph.edges must be lists")
        for i, n in enumerate(nodes):
            if not isinstance(n, Mapping) or not n.get("id") or not n.get("kind"):
                raise SkillGraphError(f"node[{i}] must carry id and kind")
            nid, name, kind = str(n["id"]), str(n.get("name") or n["id"]), str(n["kind"])
            if nid in self._nodes:
                raise SkillGraphError(f"duplicate node id {nid!r}")
            node = Node(nid, name, kind, n)
            self._nodes[nid] = node
            # Skill/category names are the planner-facing vocabulary and the
            # catalogue key: two selectable nodes sharing one name would make a
            # plan ambiguous, so it is refused here rather than at plan time.
            if kind in SKILL_KINDS or kind in ("category", "root"):
                if name in self._by_name:
                    raise SkillGraphError(
                        f"node name {name!r} claimed by both {self._by_name[name].id!r} "
                        f"and {nid!r}")
                self._by_name[name] = node
        if self.root and self.root not in self._nodes:
            raise SkillGraphError(f"root {self.root!r} is not a node")
        self._out: dict[str, dict[str, list[Mapping]]] = {}
        self._in: dict[str, dict[str, list[Mapping]]] = {}
        for i, e in enumerate(edges):
            if not isinstance(e, Mapping):
                raise SkillGraphError(f"edge[{i}] must be an object")
            rel, src, dst = e.get("relation"), e.get("source"), e.get("target")
            if rel not in RELATIONS:
                raise SkillGraphError(
                    f"edge[{i}] relation {rel!r} not in {sorted(RELATIONS)}")
            for end, label in ((src, "source"), (dst, "target")):
                if end not in self._nodes:
                    raise SkillGraphError(
                        f"edge[{i}] ({rel}) {label} {end!r} is not a node")
            if rel in ("HAS_STAGE", "DECOMPOSES_TO"):
                order = e.get("order")
                if isinstance(order, bool) or not isinstance(order, int):
                    raise SkillGraphError(
                        f"edge[{i}] ({rel} {src}->{dst}) needs an int order")
            self._out.setdefault(src, {}).setdefault(rel, []).append(e)
            self._in.setdefault(dst, {}).setdefault(rel, []).append(e)
        for rel in ("IS_A", "DECOMPOSES_TO"):
            self._assert_acyclic(rel)

    # -- construction -------------------------------------------------------
    @classmethod
    def load(cls, path: str | Path | None = None) -> UnifiedSkillGraph:
        """Read and validate the JSON at ``path`` (default: the configured
        path). A missing file is an error naming the path -- never a silent
        empty graph."""
        p = Path(path) if path is not None else default_graph_path()
        try:
            raw = p.read_bytes()
        except OSError as exc:
            raise SkillGraphError(
                f"unified skill graph not readable at {p} ({exc}); set "
                f"{GRAPH_PATH_ENV} or regenerate it with "
                "robocasa/scripts/build_skill_taxonomy.py") from exc
        try:
            data = json.loads(raw)
        except ValueError as exc:
            raise SkillGraphError(f"unified skill graph at {p} is not JSON: {exc}") from exc
        return cls(data, source=str(p), sha256=hashlib.sha256(raw).hexdigest())

    def _assert_acyclic(self, rel: str) -> None:
        state: dict[str, int] = {}  # 1 = on stack, 2 = done

        def visit(nid: str, path: list[str]) -> None:
            mark = state.get(nid, 0)
            if mark == 2:
                return
            if mark == 1:
                cycle = path[path.index(nid):] + [nid]
                raise SkillGraphError(f"{rel} cycle: {' -> '.join(cycle)}")
            state[nid] = 1
            for e in self._out.get(nid, {}).get(rel, ()):
                visit(e["target"], path + [nid])
            state[nid] = 2

        for nid in self._nodes:
            visit(nid, [])

    # -- lookups ------------------------------------------------------------
    def node(self, id_or_name: str) -> Node:
        n = self._nodes.get(id_or_name) or self._by_name.get(id_or_name)
        if n is None:
            raise SkillGraphError(f"unknown skill graph node {id_or_name!r}")
        return n

    def has(self, id_or_name: str) -> bool:
        return id_or_name in self._nodes or id_or_name in self._by_name

    def skills(self) -> tuple[Node, ...]:
        """Every selectable skill node (observed + canonical), name-sorted."""
        return tuple(sorted((n for n in self._nodes.values() if n.kind in SKILL_KINDS),
                            key=lambda n: n.name))

    def _ordered(self, nid: str, rel: str) -> list[str]:
        edges = sorted(self._out.get(nid, {}).get(rel, ()), key=lambda e: e["order"])
        return [e["target"] for e in edges]

    def canonical_parent(self, skill: str) -> str | None:
        """The IS_A parent's name (taxonomy classification), or None at the root."""
        n = self.node(skill)
        parents = self._out.get(n.id, {}).get("IS_A", ())
        return self._nodes[parents[0]["target"]].name if parents else None

    def taxonomy_path(self, skill: str) -> tuple[str, ...]:
        """Root -> ... -> skill, by IS_A (names)."""
        n = self.node(skill)
        path = [n.name]
        seen = {n.id}
        cur = n
        while True:
            parents = self._out.get(cur.id, {}).get("IS_A", ())
            if not parents:
                break
            cur = self._nodes[parents[0]["target"]]
            if cur.id in seen:  # unreachable after _assert_acyclic; belt and braces
                raise SkillGraphError(f"IS_A cycle through {cur.id!r}")
            seen.add(cur.id)
            path.append(cur.name)
        return tuple(reversed(path))

    def decomposition(self, skill: str) -> tuple[str, ...]:
        """Ordered DECOMPOSES_TO component names (ontology-authored recipe)."""
        n = self.node(skill)
        return tuple(self._nodes[t].name for t in self._ordered(n.id, "DECOMPOSES_TO"))

    def stages(self, skill: str) -> tuple[dict, ...]:
        """Ordered HAS_STAGE stages: ``{stage, name, id, realizes}`` each, where
        ``realizes`` is the REALIZES canonical name (or None)."""
        n = self.node(skill)
        out = []
        for sid in self._ordered(n.id, "HAS_STAGE"):
            s = self._nodes[sid]
            realizes = self._out.get(sid, {}).get("REALIZES", ())
            out.append({"stage": str(s.raw.get("stage") or s.name.rsplit(".", 1)[-1]),
                        "name": s.name, "id": s.id,
                        "realizes": self._nodes[realizes[0]["target"]].name
                        if realizes else None})
        return tuple(out)

    def observed_transitions(self, stage_id: str) -> tuple[dict, ...]:
        """Empirical next-stage adjacency out of one stage node (count-sorted).
        Descriptive only: an observed transition is not a precondition."""
        out = []
        for e in self._out.get(stage_id, {}).get("OBSERVED_TRANSITION", ()):
            out.append({"target": self._nodes[e["target"]].name, "target_id": e["target"],
                        "count": e.get("count"), "episode_support": e.get("episode_support")})
        return tuple(sorted(out, key=lambda d: (-(d["count"] or 0), d["target"])))

    def evidence(self, skill: str) -> Mapping[str, Any]:
        return dict(self.node(skill).raw.get("evidence") or {})

    def graph_executable_flag(self, skill: str) -> bool:
        """The annotator's ``executable`` flag -- an ontology statement, not a
        binding. Exposed under this deliberately long name so no caller mistakes
        it for ``bound``."""
        return bool(self.node(skill).raw.get("executable", False))

    # -- expansion ----------------------------------------------------------
    def expand(self, skill: str, _stack: tuple[str, ...] = ()) -> tuple[Leaf, ...]:
        """Recursively expand one skill into its leaf chain, in order.

        Rule, applied server-side (a model never expands for us):

        1. a skill with HAS_STAGE stages -> one leaf per stage, canonical from
           REALIZES (observed skills, and canonical skills carrying direct
           annotation evidence such as ``Pick``);
        2. else a skill with DECOMPOSES_TO -> the ordered components, each
           expanded recursively (``TransferObject -> Pick, Transport, Place``);
        3. else the canonical skill itself is the leaf (``PressButton``).

        Unknown skills and cycles raise ``SkillGraphError``.
        """
        n = self.node(skill)
        if n.kind not in SKILL_KINDS:
            raise SkillGraphError(
                f"{n.name!r} is a {n.kind}, not a selectable skill; expand a skill")
        if n.id in _stack:
            raise SkillGraphError(
                f"DECOMPOSES_TO cycle: {' -> '.join(_stack + (n.id,))}")
        path = self.taxonomy_path(n.name)
        stages = self.stages(n.name)
        parts = self.decomposition(n.name)
        if stages:
            # A stage's canonical interface is its REALIZES target. When the
            # annotation rule left one unlabelled (StartCoffeeMachine.execute)
            # and the ontology recipe has exactly one component per stage, the
            # component at the same position stands in -- recorded as such.
            positional = len(parts) == len(stages)
            out = []
            for i, s in enumerate(stages):
                canonical, via = s["realizes"], "HAS_STAGE+REALIZES"
                if canonical is None and positional:
                    canonical, via = parts[i], "HAS_STAGE+DECOMPOSES_TO[order]"
                elif canonical is None:
                    via = "HAS_STAGE"
                out.append(Leaf(n.name, s["stage"], canonical, via, path))
            return tuple(out)
        if parts:
            out: list[Leaf] = []
            for part in parts:
                out.extend(self.expand(part, _stack + (n.id,)))
            return tuple(out)
        canonical = n.name if n.kind == "canonical_skill" else self.canonical_parent(n.name)
        return (Leaf(n.name, None, canonical, "LEAF", path),)

    def describe(self, skill: str) -> dict:
        """The compact, model-facing card for one skill: what it is, where it
        sits, how it decomposes, and what the annotations say. No frame counts,
        no durations -- progressive disclosure keeps the prompt small."""
        n = self.node(skill)
        ev = n.raw.get("evidence") or {}
        return {
            "name": n.name,
            # ``kind`` is the DISPATCH kind a planner copies into the node (every
            # graph skill is a motion segment); the graph's own node kind rides
            # ``graph_kind`` so the two vocabularies never collide in a prompt.
            "kind": "segment",
            "graph_kind": n.kind,
            "taxonomy_path": list(self.taxonomy_path(n.name)),
            "stages": [s["stage"] for s in self.stages(n.name)],
            "decomposition": list(self.decomposition(n.name)),
            "instructions": sorted((ev.get("instructions") or {}).keys())[:6],
            "datasets": sorted(ev.get("datasets") or [])[:6],
        }

    # -- retrieval ----------------------------------------------------------
    def _text_weights(self, n: Node) -> dict[str, int]:
        weights: dict[str, int] = {}

        def add(text: Any, w: int) -> None:
            for t in tokens(str(text)):
                if weights.get(t, 0) < w:
                    weights[t] = w

        add(n.name, 3)
        ev = n.raw.get("evidence") or {}
        for ds in ev.get("datasets") or ():
            add(ds, 2)
        for instr in (ev.get("instructions") or {}):
            add(instr, 1)
        if n.raw.get("taxonomy_parent"):
            add(n.raw["taxonomy_parent"], 1)
        return weights

    def retrieve(self, query: str, k: int = 8) -> list[dict]:
        """Rank selectable skills against a natural-language query.

        Score = sum over distinct matched query tokens of the node's weight for
        that token (name 3, dataset 2, instruction/parent 1). Deterministic:
        ties break on name. Only positive scores are returned, at most ``k``.
        """
        q = sorted(set(tokens(query)))
        ranked = []
        for n in self.skills():
            w = self._text_weights(n)
            matched = [t for t in q if t in w]
            if not matched:
                continue
            ranked.append({"name": n.name, "id": n.id, "kind": n.kind,
                           "score": sum(w[t] for t in matched), "matched": matched})
        ranked.sort(key=lambda r: (-r["score"], r["name"]))
        return ranked[:k]

    def retrieve_subtree(self, query: str, k: int = 8) -> dict:
        """Progressive disclosure step one: the retrieved skills plus the
        taxonomy closure that explains them -- IS_A ancestors (categories and
        composite canonical parents), DECOMPOSES_TO components, and the
        canonical skills their stages REALIZE. Returns ``{seeds, skills,
        categories, total_skills}`` where ``skills`` is the compact candidate
        list (never the whole graph unless the query matches everything)."""
        seeds = self.retrieve(query, k)
        chosen: dict[str, dict] = {}
        categories: set[str] = set()

        def include(name: str, why: str, score: int = 0, matched: Sequence[str] = ()) -> None:
            n = self.node(name)
            if n.kind not in SKILL_KINDS:
                categories.add(n.name)
                return
            row = chosen.get(n.name)
            if row is None:
                chosen[n.name] = {"name": n.name, "kind": n.kind, "score": score,
                                  "matched": list(matched), "why": [why],
                                  "taxonomy_path": list(self.taxonomy_path(n.name))}
            else:
                row["score"] = max(row["score"], score)
                if why not in row["why"]:
                    row["why"].append(why)

        for s in seeds:
            include(s["name"], "retrieved", s["score"], s["matched"])
            for anc in self.taxonomy_path(s["name"])[:-1]:
                include(anc, f"IS_A ancestor of {s['name']}")
            for part in self.decomposition(s["name"]):
                include(part, f"DECOMPOSES_TO component of {s['name']}")
            for st in self.stages(s["name"]):
                if st["realizes"]:
                    include(st["realizes"], f"REALIZES target of {st['name']}")
        skills = sorted(chosen.values(), key=lambda r: (-r["score"], r["name"]))
        return {"seeds": seeds, "skills": skills,
                "categories": sorted(categories),
                "total_skills": len(self.skills())}

    # -- provenance ---------------------------------------------------------
    def provenance(self) -> dict:
        counts: dict[str, int] = {}
        for rels in self._out.values():
            for rel, es in rels.items():
                counts[rel] = counts.get(rel, 0) + len(es)
        return {
            "source": self.source,
            "sha256": self.sha256,
            "schema_version": self.schema_version,
            "root": self.root,
            "nodes": len(self._nodes),
            "edges": sum(counts.values()),
            "relations": dict(sorted(counts.items())),
            "relation_semantics": dict(self.relation_semantics),
            "datasets_analyzed": self.source_summary.get("datasets_discovered"),
            "episodes_analyzed": self.source_summary.get("episodes_analyzed"),
        }

    def library_snapshot(self) -> dict:
        """Return a bounded projection for skill-library and taxonomy viewers.

        The tree contains the root, categories, and selectable skills. Annotation
        stages stay embedded in their owning skill, while authored recipes stay
        separate from empirical transition evidence.
        """
        visible = {n.id for n in self._nodes.values()
                   if n.kind in SKILL_KINDS or n.kind in ("root", "category")}
        nodes = []
        for n in sorted((self._nodes[nid] for nid in visible), key=lambda x: x.name):
            parent_edges = self._out.get(n.id, {}).get("IS_A", ())
            parent = parent_edges[0]["target"] if parent_edges else None
            row = {"id": n.id, "name": n.name, "kind": n.kind,
                   "parent": parent if parent in visible else None,
                   "taxonomy_path": list(self.taxonomy_path(n.name)),
                   "graph_executable": bool(n.raw.get("executable", False))}
            if n.kind in SKILL_KINDS:
                ev = n.raw.get("evidence") or {}
                row.update({
                    "stages": [dict(stage) for stage in self.stages(n.name)],
                    "decomposition": list(self.decomposition(n.name)),
                    "evidence": {
                        "datasets": sorted(ev.get("datasets") or []),
                        "instructions": [
                            {"text": text, "count": count}
                            for text, count in sorted(
                                (ev.get("instructions") or {}).items(),
                                key=lambda item: (-item[1], item[0]))[:12]
                        ],
                        "episodes": ev.get("episode_support"),
                        "frames": ev.get("frames"),
                    },
                })
            nodes.append(row)
        recipes = []
        for n in self.skills():
            parts = self.decomposition(n.name)
            if parts:
                recipes.append({"skill": n.name, "steps": list(parts)})
        return {"root": self.root, "nodes": nodes,
                "recipes": sorted(recipes, key=lambda row: row["skill"])}


# --- module-level cache -----------------------------------------------------

_CACHE: dict[str, tuple[float, int, UnifiedSkillGraph]] = {}


def load_graph(path: str | Path | None = None) -> UnifiedSkillGraph:
    """``UnifiedSkillGraph.load`` behind an (mtime, size) cache, so a resident
    board process re-parses the 170 KB document only when the file changes."""
    p = Path(path) if path is not None else default_graph_path()
    key = str(p)
    try:
        st = p.stat()
    except OSError:
        _CACHE.pop(key, None)
        return UnifiedSkillGraph.load(p)  # raises the loud SkillGraphError
    hit = _CACHE.get(key)
    if hit and hit[0] == st.st_mtime and hit[1] == st.st_size:
        return hit[2]
    g = UnifiedSkillGraph.load(p)
    _CACHE[key] = (st.st_mtime, st.st_size, g)
    return g


def leaf_chain(graph: UnifiedSkillGraph, skills: Iterable[str]) -> list[Leaf]:
    """Expand an ordered sequence of skills into one flat leaf chain."""
    out: list[Leaf] = []
    for s in skills:
        out.extend(graph.expand(s))
    return out
